Name:           ros-indigo-concert-service-indoor-2d-map-prep
Version:        0.1.8
Release:        0%{?dist}
Summary:        ROS concert_service_indoor_2d_map_prep package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/concert_service_indoor_2d_map_prep
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-concert-msgs
Requires:       ros-indigo-concert-scheduler-requests
Requires:       ros-indigo-concert-service-msgs
Requires:       ros-indigo-concert-service-utilities
Requires:       ros-indigo-rocon-python-comms
Requires:       ros-indigo-rocon-std-msgs
Requires:       ros-indigo-rocon-uri
Requires:       ros-indigo-rospy
Requires:       ros-indigo-scheduler-msgs
Requires:       ros-indigo-unique-id
BuildRequires:  ros-indigo-catkin

%description
Services to initilise indoor 2d map environment. Make a map and annotation

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Feb 27 2015 Jihoon Lee <jihoonlee.in@gmail.com> - 0.1.8-0
- Autogenerated by Bloom

* Mon Feb 09 2015 Jihoon Lee <jihoonlee.in@gmail.com> - 0.1.7-0
- Autogenerated by Bloom

* Mon Jan 05 2015 Jihoon Lee <jihoonlee.in@gmail.com> - 0.1.6-0
- Autogenerated by Bloom

